# Generated by Django 3.1.5 on 2021-03-17 08:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alllisting_bid_closedbid_comment_listing_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
