# Generated by Django 3.1.5 on 2021-03-17 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210317_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='create',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='updated',
        ),
    ]
